---
version: "1"
services:
  - type: web
    name: hexlet-fastify
    runtime: node
    repo: https://github.com/ixth/fastify-web-development-project-6
    plan: free
    autoDeploy: false
    envVars:
      - key: FASTIFY_PORT
        sync: false
      - key: FASTIFY_ADDRESS
        sync: false
      - key: SESSION_KEY
        sync: false
    region: frankfurt
    buildCommand: npm ci && npm run build
    startCommand: knex migrate:latest && npm run start
